openapi: 3.0.0
paths:
  /definitions:
    post:
      operationId: DefinitionsController_create
      parameters: []
      responses:
        "201":
          description: ""
      tags: &a1
        - Definitions
    get:
      operationId: DefinitionsController_findAll
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a1
  /definitions/schema:
    get:
      operationId: DefinitionsController_getSchema
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a1
  /definitions/{id}:
    get:
      operationId: DefinitionsController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
      tags: *a1
    patch:
      operationId: DefinitionsController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
      tags: *a1
    delete:
      operationId: DefinitionsController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
      tags: *a1
  /assignments:
    post:
      operationId: AssignmentsController_create
      parameters: []
      responses:
        "201":
          description: ""
      tags: &a2
        - Assignments
    get:
      operationId: AssignmentsController_findAll
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a2
  /assignments/{id}:
    get:
      operationId: AssignmentsController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
      tags: *a2
    patch:
      operationId: AssignmentsController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
      tags: *a2
    delete:
      operationId: AssignmentsController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
      tags: *a2
  /values:
    post:
      operationId: ValuesController_create
      parameters: []
      responses:
        "201":
          description: ""
      tags: &a3
        - Values
    get:
      operationId: ValuesController_findByEntity
      parameters:
        - name: entity_id
          required: true
          in: query
          schema:
            type: string
      responses:
        "200":
          description: ""
      tags: *a3
  /filters/search:
    post:
      operationId: FiltersController_search
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FiltersSearchDto"
      responses:
        "201":
          description: ""
      tags:
        - Filters
info:
  title: Custom Fields Service
  description: API documentation for Custom Fields microservice
  version: "1.0"
  contact: {}
tags: []
servers: []
components:
  schemas:
    FiltersSearchDto:
      type: object
      properties: {}
